services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./sql_scripts/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: Azura
      MYSQL_USER: root
      MYSQL_PASSWORD: youshouldhireryan
      MYSQL_ROOT_PASSWORD: youshouldhireryan
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - azuranet

  # nodeapp:
  #   container_name: nodeappcontainer
  #   build: .
  #   image: nodeapp:v1
  #   volumes:
  #     - $HOME/nodeapp:/app
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  #   environment:
  #     HOST: 0.0.0.0
  #     PORT: 3000
  #     DB_PORT: 3306
  #     DB_USER: 'root'
  #     DB_PASSWORD: 'youshouldhireryan'
  #     DB_NAME: 'Azura'
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: nodeappservice
  #   depends_on:
  #     - mysqldb
  #   networks:
  #     - azuranet

networks:
  azuranet:
    driver: bridge
